### ISSUE TITLE
Consider Tree Sorting Algorithms

### ISSUE THREAD

**Issue by NTU-ASH** [NTU-ASH/tree-generator#17]
Consider how the node class will arrange the nodes within a tree to post, pre and in order traversal types.

**Comment by sburdon96** [comment]
[Tree.algorithms.txt](https://github.com/NTU-ASH/tree-generator/files/875446/Tree.algorithms.txt)
edited as found an error


 A text file containing code for each of the sorting algorithms. Is this what you wanted me to do/look correct? If so i'll actually write it into the code.

May need some tweaks but that will become more obvious when I actually add it to our code. Plus the output is just to show where we would add it to the traversal list.

**Comment by NTU-ASH** [comment]
Complete! :)

**Comment by NTU-JACK** [comment]
I think you should consider this more
